# Generated by Django 2.2.6 on 2019-12-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=250, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='time_period',
            field=models.CharField(choices=[('W', 'One week'), ('2W', 'Two weeks'), ('M', 'One month'), ('2M', 'Two months'), ('6M', 'Six months'), ('Y', 'All year!'), ('NA', 'Dont want to commit to a time period')], max_length=30, verbose_name='How long do you want to focus on this goal?'),
        ),
    ]
