# Generated by Django 2.2.7 on 2020-01-02 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200102_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.CharField(default=datetime.datetime(2020, 1, 2, 18, 2, 52, 651127), max_length=15),
        ),
        migrations.AlterField(
            model_name='entry',
            name='notes',
            field=models.TextField(verbose_name='Entry'),
        ),
    ]
