# Generated by Django 2.2.7 on 2020-01-02 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200102_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.CharField(default=datetime.datetime(2020, 1, 2, 18, 3, 45, 330747), max_length=15),
        ),
    ]
